// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6fvrJ5PYIXEbjV6TnNRlZWWUpmlkYxWg',
    appId: '1:689019733021:web:491dba14cecbc9e474f2f4',
    messagingSenderId: '689019733021',
    projectId: 'ecommerce-app-82178',
    authDomain: 'ecommerce-app-82178.firebaseapp.com',
    storageBucket: 'ecommerce-app-82178.appspot.com',
    measurementId: 'G-91XR94DQLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFj7XKg2rmm1ltntzsZc0xOy7bLsMF60Q',
    appId: '1:689019733021:android:7077a7d162c94a5074f2f4',
    messagingSenderId: '689019733021',
    projectId: 'ecommerce-app-82178',
    storageBucket: 'ecommerce-app-82178.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6TUEIvmwVPH-qRa8t_NVTdFmU-m5jBFU',
    appId: '1:689019733021:ios:1ebabbe80be4a93674f2f4',
    messagingSenderId: '689019733021',
    projectId: 'ecommerce-app-82178',
    storageBucket: 'ecommerce-app-82178.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6TUEIvmwVPH-qRa8t_NVTdFmU-m5jBFU',
    appId: '1:689019733021:ios:03c5a7580d82e10274f2f4',
    messagingSenderId: '689019733021',
    projectId: 'ecommerce-app-82178',
    storageBucket: 'ecommerce-app-82178.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
