// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVuqjEitIhBH1bAT7jhS66voff5gkg30Q',
    appId: '1:710671663631:web:6152965f8b7d5ca856597a',
    messagingSenderId: '710671663631',
    projectId: 'multiply-mcq',
    authDomain: 'multiply-mcq.firebaseapp.com',
    storageBucket: 'multiply-mcq.appspot.com',
    measurementId: 'G-181370V95W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdsmlFQA42ZdGHiG2XJvgBcqmuYYDce0I',
    appId: '1:710671663631:android:f189e3bf9c95ed3256597a',
    messagingSenderId: '710671663631',
    projectId: 'multiply-mcq',
    storageBucket: 'multiply-mcq.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU98yxnsji97Sr3fgQY7PnweqRxpGj_Lk',
    appId: '1:710671663631:ios:9afb88afe91161f956597a',
    messagingSenderId: '710671663631',
    projectId: 'multiply-mcq',
    storageBucket: 'multiply-mcq.appspot.com',
    iosBundleId: 'com.example.mcq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU98yxnsji97Sr3fgQY7PnweqRxpGj_Lk',
    appId: '1:710671663631:ios:4a3036dd9f94f36156597a',
    messagingSenderId: '710671663631',
    projectId: 'multiply-mcq',
    storageBucket: 'multiply-mcq.appspot.com',
    iosBundleId: 'com.example.mcq.RunnerTests',
  );
}
